name: Build and Upload ApexCharts for Vaadin

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set version from tag and build
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          mvn versions:set -B -DnewVersion=${TAG_NAME#v}
          mvn clean install -B -Pdirectory

      - name: Create new GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload assembled build artifact to Vaadin Add-on directory
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          curl -X POST "https://vaadin.com/vaadincom/directory-service/upload/apexchartsjs?authKey=${{ secrets.VAADIN_AUTH_KEY }}" \
            -H "accept: */*" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@target/apexcharts-${TAG_NAME#v}.zip;type=application/zip"